#!/usr/bin/env bash
# Script that configures nginx server with custom 404 page

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple index.html with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx with redirection and custom 404 page
sed -i '/server_name _;/a\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart